// verbs.js — Japanese Verb Database
// Format: { kanji, kana, meaning, group, jlpt, options? }
// group: 1 = 五段動詞, 2 = 一段動詞, 3 = 不規則動詞
// jlpt: "N5" | "N4" | "N3" | "N2" | "N1"
// options.irregular_ta: true → 行く type (ta-form uses った not いた)

const VERBS = [
  // ===== GROUP 1 — う ending =====
  { kanji:"買う",    kana:"かう",      meaning:"買",        group:1, jlpt:"N5" },
  { kanji:"使う",    kana:"つかう",    meaning:"使用",      group:1, jlpt:"N4" },
  { kanji:"洗う",    kana:"あらう",    meaning:"洗",        group:1, jlpt:"N4" },
  { kanji:"歌う",    kana:"うたう",    meaning:"唱歌",      group:1, jlpt:"N4" },
  { kanji:"笑う",    kana:"わらう",    meaning:"笑",        group:1, jlpt:"N4" },
  { kanji:"言う",    kana:"いう",      meaning:"說",        group:1, jlpt:"N5" },
  { kanji:"会う",    kana:"あう",      meaning:"見面",      group:1, jlpt:"N5" },
  { kanji:"習う",    kana:"ならう",    meaning:"學習",      group:1, jlpt:"N4" },
  { kanji:"手伝う",  kana:"てつだう",  meaning:"幫忙",      group:1, jlpt:"N4" },
  { kanji:"吸う",    kana:"すう",      meaning:"吸",        group:1, jlpt:"N4" },
  { kanji:"通う",    kana:"かよう",    meaning:"往返",      group:1, jlpt:"N3" },
  { kanji:"払う",    kana:"はらう",    meaning:"支付",      group:1, jlpt:"N4" },
  { kanji:"思う",    kana:"おもう",    meaning:"認為、覺得", group:1, jlpt:"N5" },
  { kanji:"願う",    kana:"ねがう",    meaning:"希望",      group:1, jlpt:"N3" },
  { kanji:"拾う",    kana:"ひろう",    meaning:"撿",        group:1, jlpt:"N4" },
  { kanji:"失う",    kana:"うしなう",  meaning:"失去",      group:1, jlpt:"N2" },
  { kanji:"向かう",  kana:"むかう",    meaning:"面向、前往", group:1, jlpt:"N3" },
  { kanji:"問う",    kana:"とう",      meaning:"詢問",      group:1, jlpt:"N2" },
  { kanji:"誓う",    kana:"ちかう",    meaning:"發誓",      group:1, jlpt:"N1" },
  { kanji:"追う",    kana:"おう",      meaning:"追",        group:1, jlpt:"N3" },
  { kanji:"扱う",    kana:"あつかう",  meaning:"處理、對待", group:1, jlpt:"N2" },
  { kanji:"伺う",    kana:"うかがう",  meaning:"拜訪（謙）", group:1, jlpt:"N2" },

  // ===== GROUP 1 — く ending =====
  { kanji:"書く",    kana:"かく",      meaning:"寫",        group:1, jlpt:"N5" },
  { kanji:"聞く",    kana:"きく",      meaning:"聽、問",    group:1, jlpt:"N5" },
  { kanji:"歩く",    kana:"あるく",    meaning:"走路",      group:1, jlpt:"N5" },
  { kanji:"働く",    kana:"はたらく",  meaning:"工作",      group:1, jlpt:"N4" },
  { kanji:"着く",    kana:"つく",      meaning:"抵達",      group:1, jlpt:"N4" },
  { kanji:"行く",    kana:"いく",      meaning:"去",        group:1, jlpt:"N5", irregular:{ ta:"った" } },
  { kanji:"置く",    kana:"おく",      meaning:"放置",      group:1, jlpt:"N4" },
  { kanji:"動く",    kana:"うごく",    meaning:"移動",      group:1, jlpt:"N4" },
  { kanji:"続く",    kana:"つづく",    meaning:"持續",      group:1, jlpt:"N3" },
  { kanji:"焼く",    kana:"やく",      meaning:"烤",        group:1, jlpt:"N4" },
  { kanji:"磨く",    kana:"みがく",    meaning:"刷牙、磨",  group:1, jlpt:"N4" },
  { kanji:"描く",    kana:"えがく",    meaning:"描繪",      group:1, jlpt:"N3" },
  { kanji:"弾く",    kana:"ひく",      meaning:"彈奏",      group:1, jlpt:"N3" },
  { kanji:"開く",    kana:"ひらく",    meaning:"打開",      group:1, jlpt:"N3" },
  { kanji:"引く",    kana:"ひく",      meaning:"拉",        group:1, jlpt:"N3" },
  { kanji:"叩く",    kana:"たたく",    meaning:"敲打",      group:1, jlpt:"N3" },
  { kanji:"気づく",  kana:"きづく",    meaning:"注意到",    group:1, jlpt:"N3" },
  { kanji:"輝く",    kana:"かがやく",  meaning:"閃耀",      group:1, jlpt:"N2" },
  { kanji:"導く",    kana:"みちびく",  meaning:"引導",      group:1, jlpt:"N2" },
  { kanji:"解く",    kana:"とく",      meaning:"解開、解答", group:1, jlpt:"N3" },
  { kanji:"招く",    kana:"まねく",    meaning:"邀請",      group:1, jlpt:"N3" },
  { kanji:"築く",    kana:"きずく",    meaning:"建立",      group:1, jlpt:"N2" },
  { kanji:"向く",    kana:"むく",      meaning:"面向",      group:1, jlpt:"N3" },
  { kanji:"抜く",    kana:"ぬく",      meaning:"拔出",      group:1, jlpt:"N3" },
  { kanji:"除く",    kana:"のぞく",    meaning:"除外",      group:1, jlpt:"N2" },
  { kanji:"咲く",    kana:"さく",      meaning:"開花",      group:1, jlpt:"N3" },
  { kanji:"説く",    kana:"とく",      meaning:"說服",      group:1, jlpt:"N1" },
  { kanji:"効く",    kana:"きく",      meaning:"有效",      group:1, jlpt:"N3" },
  { kanji:"届く",    kana:"とどく",    meaning:"送達",      group:1, jlpt:"N3" },
  { kanji:"浮く",    kana:"うく",      meaning:"浮起",      group:1, jlpt:"N3" },

  // ===== GROUP 1 — ぐ ending =====
  { kanji:"泳ぐ",    kana:"およぐ",    meaning:"游泳",      group:1, jlpt:"N5" },
  { kanji:"急ぐ",    kana:"いそぐ",    meaning:"趕快",      group:1, jlpt:"N4" },
  { kanji:"脱ぐ",    kana:"ぬぐ",      meaning:"脫衣服",    group:1, jlpt:"N4" },
  { kanji:"注ぐ",    kana:"そそぐ",    meaning:"倒、注入",  group:1, jlpt:"N3" },
  { kanji:"繋ぐ",    kana:"つなぐ",    meaning:"連接",      group:1, jlpt:"N2" },
  { kanji:"騒ぐ",    kana:"さわぐ",    meaning:"喧鬧",      group:1, jlpt:"N3" },
  { kanji:"稼ぐ",    kana:"かせぐ",    meaning:"賺錢",      group:1, jlpt:"N3" },
  { kanji:"防ぐ",    kana:"ふせぐ",    meaning:"防止",      group:1, jlpt:"N2" },
  { kanji:"漕ぐ",    kana:"こぐ",      meaning:"划（船）",  group:1, jlpt:"N1" },
  { kanji:"嗅ぐ",    kana:"かぐ",      meaning:"聞（氣味）", group:1, jlpt:"N1" },

  // ===== GROUP 1 — す ending =====
  { kanji:"話す",    kana:"はなす",    meaning:"說話",      group:1, jlpt:"N5" },
  { kanji:"貸す",    kana:"かす",      meaning:"借出",      group:1, jlpt:"N4" },
  { kanji:"渡す",    kana:"わたす",    meaning:"交給",      group:1, jlpt:"N4" },
  { kanji:"返す",    kana:"かえす",    meaning:"歸還",      group:1, jlpt:"N4" },
  { kanji:"消す",    kana:"けす",      meaning:"關掉、消除", group:1, jlpt:"N4" },
  { kanji:"探す",    kana:"さがす",    meaning:"尋找",      group:1, jlpt:"N4" },
  { kanji:"出す",    kana:"だす",      meaning:"拿出、提出", group:1, jlpt:"N4" },
  { kanji:"押す",    kana:"おす",      meaning:"推、按",    group:1, jlpt:"N4" },
  { kanji:"回す",    kana:"まわす",    meaning:"轉動",      group:1, jlpt:"N3" },
  { kanji:"落とす",  kana:"おとす",    meaning:"掉落",      group:1, jlpt:"N4" },
  { kanji:"外す",    kana:"はずす",    meaning:"取下",      group:1, jlpt:"N3" },
  { kanji:"起こす",  kana:"おこす",    meaning:"叫醒、引起", group:1, jlpt:"N3" },
  { kanji:"直す",    kana:"なおす",    meaning:"修正",      group:1, jlpt:"N4" },
  { kanji:"移す",    kana:"うつす",    meaning:"移動",      group:1, jlpt:"N3" },
  { kanji:"示す",    kana:"しめす",    meaning:"示意",      group:1, jlpt:"N3" },
  { kanji:"流す",    kana:"ながす",    meaning:"沖走",      group:1, jlpt:"N3" },
  { kanji:"殺す",    kana:"ころす",    meaning:"殺",        group:1, jlpt:"N3" },
  { kanji:"放す",    kana:"はなす",    meaning:"放開",      group:1, jlpt:"N3" },
  { kanji:"残す",    kana:"のこす",    meaning:"留下",      group:1, jlpt:"N3" },
  { kanji:"隠す",    kana:"かくす",    meaning:"隱藏",      group:1, jlpt:"N3" },
  { kanji:"許す",    kana:"ゆるす",    meaning:"原諒、允許", group:1, jlpt:"N3" },
  { kanji:"表す",    kana:"あらわす",  meaning:"表達",      group:1, jlpt:"N2" },
  { kanji:"申す",    kana:"もうす",    meaning:"說（謙）",  group:1, jlpt:"N3" },
  { kanji:"越す",    kana:"こす",      meaning:"超越",      group:1, jlpt:"N2" },
  { kanji:"貸し出す",kana:"かしだす",  meaning:"借出",      group:1, jlpt:"N3" },
  { kanji:"指す",    kana:"さす",      meaning:"指",        group:1, jlpt:"N3" },
  { kanji:"刺す",    kana:"さす",      meaning:"刺",        group:1, jlpt:"N3" },
  { kanji:"増す",    kana:"ます",      meaning:"增加",      group:1, jlpt:"N2" },
  { kanji:"冷やす",  kana:"ひやす",    meaning:"冷卻",      group:1, jlpt:"N3" },

  // ===== GROUP 1 — つ ending =====
  { kanji:"待つ",    kana:"まつ",      meaning:"等待",      group:1, jlpt:"N5" },
  { kanji:"立つ",    kana:"たつ",      meaning:"站立",      group:1, jlpt:"N4" },
  { kanji:"打つ",    kana:"うつ",      meaning:"打擊",      group:1, jlpt:"N3" },
  { kanji:"勝つ",    kana:"かつ",      meaning:"勝利",      group:1, jlpt:"N4" },
  { kanji:"持つ",    kana:"もつ",      meaning:"拿、持有",  group:1, jlpt:"N5" },
  { kanji:"育つ",    kana:"そだつ",    meaning:"成長",      group:1, jlpt:"N3" },
  { kanji:"発つ",    kana:"たつ",      meaning:"出發",      group:1, jlpt:"N3" },
  { kanji:"経つ",    kana:"たつ",      meaning:"（時間）經過", group:1, jlpt:"N3" },
  { kanji:"保つ",    kana:"たもつ",    meaning:"維持",      group:1, jlpt:"N2" },
  { kanji:"絶つ",    kana:"たつ",      meaning:"斷絕",      group:1, jlpt:"N2" },

  // ===== GROUP 1 — ぬ ending =====
  { kanji:"死ぬ",    kana:"しぬ",      meaning:"死",        group:1, jlpt:"N4" },

  // ===== GROUP 1 — ぶ ending =====
  { kanji:"遊ぶ",    kana:"あそぶ",    meaning:"玩",        group:1, jlpt:"N5" },
  { kanji:"呼ぶ",    kana:"よぶ",      meaning:"呼叫",      group:1, jlpt:"N4" },
  { kanji:"飛ぶ",    kana:"とぶ",      meaning:"飛",        group:1, jlpt:"N4" },
  { kanji:"選ぶ",    kana:"えらぶ",    meaning:"選擇",      group:1, jlpt:"N3" },
  { kanji:"喜ぶ",    kana:"よろこぶ",  meaning:"高興",      group:1, jlpt:"N3" },
  { kanji:"学ぶ",    kana:"まなぶ",    meaning:"學習",      group:1, jlpt:"N3" },
  { kanji:"運ぶ",    kana:"はこぶ",    meaning:"搬運",      group:1, jlpt:"N3" },
  { kanji:"結ぶ",    kana:"むすぶ",    meaning:"綁、結",    group:1, jlpt:"N3" },
  { kanji:"浮かぶ",  kana:"うかぶ",    meaning:"浮現",      group:1, jlpt:"N3" },
  { kanji:"叫ぶ",    kana:"さけぶ",    meaning:"呼喊",      group:1, jlpt:"N3" },
  { kanji:"跳ぶ",    kana:"とぶ",      meaning:"跳",        group:1, jlpt:"N3" },
  { kanji:"転ぶ",    kana:"ころぶ",    meaning:"跌倒",      group:1, jlpt:"N3" },
  { kanji:"並ぶ",    kana:"ならぶ",    meaning:"排隊",      group:1, jlpt:"N4" },
  { kanji:"及ぶ",    kana:"およぶ",    meaning:"及、達到",  group:1, jlpt:"N2" },
  { kanji:"忍ぶ",    kana:"しのぶ",    meaning:"忍耐",      group:1, jlpt:"N1" },

  // ===== GROUP 1 — む ending =====
  { kanji:"飲む",    kana:"のむ",      meaning:"喝",        group:1, jlpt:"N5" },
  { kanji:"読む",    kana:"よむ",      meaning:"讀",        group:1, jlpt:"N5" },
  { kanji:"休む",    kana:"やすむ",    meaning:"休息",      group:1, jlpt:"N5" },
  { kanji:"住む",    kana:"すむ",      meaning:"居住",      group:1, jlpt:"N4" },
  { kanji:"頼む",    kana:"たのむ",    meaning:"拜託",      group:1, jlpt:"N4" },
  { kanji:"組む",    kana:"くむ",      meaning:"組合",      group:1, jlpt:"N3" },
  { kanji:"楽しむ",  kana:"たのしむ",  meaning:"享受",      group:1, jlpt:"N3" },
  { kanji:"悩む",    kana:"なやむ",    meaning:"煩惱",      group:1, jlpt:"N3" },
  { kanji:"進む",    kana:"すすむ",    meaning:"前進",      group:1, jlpt:"N3" },
  { kanji:"積む",    kana:"つむ",      meaning:"堆疊",      group:1, jlpt:"N3" },
  { kanji:"済む",    kana:"すむ",      meaning:"完成",      group:1, jlpt:"N3" },
  { kanji:"踏む",    kana:"ふむ",      meaning:"踩",        group:1, jlpt:"N3" },
  { kanji:"包む",    kana:"つつむ",    meaning:"包",        group:1, jlpt:"N3" },
  { kanji:"盗む",    kana:"ぬすむ",    meaning:"偷竊",      group:1, jlpt:"N3" },
  { kanji:"望む",    kana:"のぞむ",    meaning:"希望",      group:1, jlpt:"N3" },
  { kanji:"好む",    kana:"このむ",    meaning:"喜歡",      group:1, jlpt:"N2" },
  { kanji:"込む",    kana:"こむ",      meaning:"擁擠",      group:1, jlpt:"N3" },
  { kanji:"沈む",    kana:"しずむ",    meaning:"沉沒",      group:1, jlpt:"N3" },
  { kanji:"産む",    kana:"うむ",      meaning:"生產",      group:1, jlpt:"N3" },
  { kanji:"膨らむ",  kana:"ふくらむ",  meaning:"膨脹",      group:1, jlpt:"N2" },
  { kanji:"苦しむ",  kana:"くるしむ",  meaning:"痛苦",      group:1, jlpt:"N3" },
  { kanji:"悲しむ",  kana:"かなしむ",  meaning:"悲傷",      group:1, jlpt:"N3" },

  // ===== GROUP 1 — る ending (G1) =====
  { kanji:"分かる",  kana:"わかる",    meaning:"理解",      group:1, jlpt:"N5" },
  { kanji:"帰る",    kana:"かえる",    meaning:"回家",      group:1, jlpt:"N5" },
  { kanji:"作る",    kana:"つくる",    meaning:"製作",      group:1, jlpt:"N5" },
  { kanji:"送る",    kana:"おくる",    meaning:"傳送",      group:1, jlpt:"N4" },
  { kanji:"乗る",    kana:"のる",      meaning:"搭乘",      group:1, jlpt:"N5" },
  { kanji:"走る",    kana:"はしる",    meaning:"跑",        group:1, jlpt:"N5" },
  { kanji:"知る",    kana:"しる",      meaning:"知道",      group:1, jlpt:"N5" },
  { kanji:"入る",    kana:"はいる",    meaning:"進入",      group:1, jlpt:"N5" },
  { kanji:"切る",    kana:"きる",      meaning:"切",        group:1, jlpt:"N5" },
  { kanji:"降る",    kana:"ふる",      meaning:"下（雨雪）", group:1, jlpt:"N4" },
  { kanji:"取る",    kana:"とる",      meaning:"取",        group:1, jlpt:"N5" },
  { kanji:"起こる",  kana:"おこる",    meaning:"發生",      group:1, jlpt:"N4" },
  { kanji:"始まる",  kana:"はじまる",  meaning:"開始",      group:1, jlpt:"N4" },
  { kanji:"終わる",  kana:"おわる",    meaning:"結束",      group:1, jlpt:"N4" },
  { kanji:"変わる",  kana:"かわる",    meaning:"改變",      group:1, jlpt:"N4" },
  { kanji:"鳴る",    kana:"なる",      meaning:"響起",      group:1, jlpt:"N4" },
  { kanji:"売る",    kana:"うる",      meaning:"賣",        group:1, jlpt:"N4" },
  { kanji:"折る",    kana:"おる",      meaning:"折",        group:1, jlpt:"N3" },
  { kanji:"困る",    kana:"こまる",    meaning:"困擾",      group:1, jlpt:"N4" },
  { kanji:"触る",    kana:"さわる",    meaning:"碰觸",      group:1, jlpt:"N4" },
  { kanji:"散る",    kana:"ちる",      meaning:"散落",      group:1, jlpt:"N3" },
  { kanji:"光る",    kana:"ひかる",    meaning:"發光",      group:1, jlpt:"N3" },
  { kanji:"残る",    kana:"のこる",    meaning:"剩下",      group:1, jlpt:"N3" },
  { kanji:"回る",    kana:"まわる",    meaning:"旋轉",      group:1, jlpt:"N3" },
  { kanji:"眠る",    kana:"ねむる",    meaning:"睡眠",      group:1, jlpt:"N4" },
  { kanji:"怒る",    kana:"おこる",    meaning:"生氣",      group:1, jlpt:"N4" },
  { kanji:"頑張る",  kana:"がんばる",  meaning:"加油努力",  group:1, jlpt:"N4" },
  { kanji:"戻る",    kana:"もどる",    meaning:"返回",      group:1, jlpt:"N4" },
  { kanji:"曲がる",  kana:"まがる",    meaning:"轉彎",      group:1, jlpt:"N4" },
  { kanji:"上がる",  kana:"あがる",    meaning:"上升",      group:1, jlpt:"N4" },
  { kanji:"下がる",  kana:"さがる",    meaning:"下降",      group:1, jlpt:"N4" },
  { kanji:"集まる",  kana:"あつまる",  meaning:"聚集",      group:1, jlpt:"N4" },
  { kanji:"限る",    kana:"かぎる",    meaning:"限制",      group:1, jlpt:"N3" },
  { kanji:"しゃべる",kana:"しゃべる",  meaning:"聊天",      group:1, jlpt:"N3" },
  { kanji:"蹴る",    kana:"ける",      meaning:"踢",        group:1, jlpt:"N3" },
  { kanji:"貼る",    kana:"はる",      meaning:"貼",        group:1, jlpt:"N4" },
  { kanji:"渡る",    kana:"わたる",    meaning:"渡過",      group:1, jlpt:"N4" },
  { kanji:"広がる",  kana:"ひろがる",  meaning:"擴散",      group:1, jlpt:"N3" },
  { kanji:"腐る",    kana:"くさる",    meaning:"腐爛",      group:1, jlpt:"N3" },
  { kanji:"被る",    kana:"かぶる",    meaning:"戴（帽子）", group:1, jlpt:"N4" },
  { kanji:"滑る",    kana:"すべる",    meaning:"滑",        group:1, jlpt:"N3" },
  { kanji:"減る",    kana:"へる",      meaning:"減少",      group:1, jlpt:"N3" },
  { kanji:"握る",    kana:"にぎる",    meaning:"握",        group:1, jlpt:"N3" },
  { kanji:"誇る",    kana:"ほこる",    meaning:"驕傲",      group:1, jlpt:"N2" },
  { kanji:"配る",    kana:"くばる",    meaning:"分發",      group:1, jlpt:"N3" },
  { kanji:"守る",    kana:"まもる",    meaning:"守護",      group:1, jlpt:"N3" },
  { kanji:"語る",    kana:"かたる",    meaning:"訴說",      group:1, jlpt:"N2" },
  { kanji:"計る",    kana:"はかる",    meaning:"測量",      group:1, jlpt:"N3" },
  { kanji:"謝る",    kana:"あやまる",  meaning:"道歉",      group:1, jlpt:"N3" },
  { kanji:"塗る",    kana:"ぬる",      meaning:"塗",        group:1, jlpt:"N3" },
  { kanji:"飾る",    kana:"かざる",    meaning:"裝飾",      group:1, jlpt:"N3" },
  { kanji:"寄る",    kana:"よる",      meaning:"靠近",      group:1, jlpt:"N3" },
  { kanji:"通る",    kana:"とおる",    meaning:"通過",      group:1, jlpt:"N4" },
  { kanji:"頼る",    kana:"たよる",    meaning:"依靠",      group:1, jlpt:"N3" },
  { kanji:"負う",    kana:"おう",      meaning:"負責",      group:1, jlpt:"N2" },
  { kanji:"かかる",  kana:"かかる",    meaning:"花費（時間/費用）", group:1, jlpt:"N5" },
  { kanji:"なる",    kana:"なる",      meaning:"成為",      group:1, jlpt:"N5" },
  { kanji:"はじまる",kana:"はじまる",  meaning:"開始",      group:1, jlpt:"N4" },
  { kanji:"おわる",  kana:"おわる",    meaning:"結束",      group:1, jlpt:"N4" },

  // ===== GROUP 2 — 一段動詞 =====
  { kanji:"食べる",  kana:"たべる",    meaning:"吃",        group:2, jlpt:"N5" },
  { kanji:"見る",    kana:"みる",      meaning:"看",        group:2, jlpt:"N5" },
  { kanji:"起きる",  kana:"おきる",    meaning:"起床",      group:2, jlpt:"N5" },
  { kanji:"寝る",    kana:"ねる",      meaning:"睡覺",      group:2, jlpt:"N5" },
  { kanji:"着る",    kana:"きる",      meaning:"穿（衣服）", group:2, jlpt:"N5" },
  { kanji:"出る",    kana:"でる",      meaning:"出去",      group:2, jlpt:"N4" },
  { kanji:"教える",  kana:"おしえる",  meaning:"教",        group:2, jlpt:"N5" },
  { kanji:"開ける",  kana:"あける",    meaning:"打開",      group:2, jlpt:"N5" },
  { kanji:"閉める",  kana:"しめる",    meaning:"關閉",      group:2, jlpt:"N4" },
  { kanji:"答える",  kana:"こたえる",  meaning:"回答",      group:2, jlpt:"N4" },
  { kanji:"覚える",  kana:"おぼえる",  meaning:"記住",      group:2, jlpt:"N4" },
  { kanji:"忘れる",  kana:"わすれる",  meaning:"忘記",      group:2, jlpt:"N4" },
  { kanji:"受ける",  kana:"うける",    meaning:"接受",      group:2, jlpt:"N3" },
  { kanji:"入れる",  kana:"いれる",    meaning:"放入",      group:2, jlpt:"N5" },
  { kanji:"出かける",kana:"でかける",  meaning:"外出",      group:2, jlpt:"N5" },
  { kanji:"助ける",  kana:"たすける",  meaning:"幫助",      group:2, jlpt:"N4" },
  { kanji:"集める",  kana:"あつめる",  meaning:"收集",      group:2, jlpt:"N4" },
  { kanji:"変える",  kana:"かえる",    meaning:"改變（他）", group:2, jlpt:"N4" },
  { kanji:"上げる",  kana:"あげる",    meaning:"提高、給",  group:2, jlpt:"N4" },
  { kanji:"下げる",  kana:"さげる",    meaning:"降低",      group:2, jlpt:"N4" },
  { kanji:"決める",  kana:"きめる",    meaning:"決定",      group:2, jlpt:"N4" },
  { kanji:"始める",  kana:"はじめる",  meaning:"開始（他）", group:2, jlpt:"N4" },
  { kanji:"続ける",  kana:"つづける",  meaning:"繼續",      group:2, jlpt:"N3" },
  { kanji:"止める",  kana:"とめる",    meaning:"停止",      group:2, jlpt:"N4" },
  { kanji:"倒れる",  kana:"たおれる",  meaning:"倒下",      group:2, jlpt:"N3" },
  { kanji:"生まれる",kana:"うまれる",  meaning:"出生",      group:2, jlpt:"N4" },
  { kanji:"消える",  kana:"きえる",    meaning:"消失",      group:2, jlpt:"N4" },
  { kanji:"見える",  kana:"みえる",    meaning:"看得見",    group:2, jlpt:"N4" },
  { kanji:"聞こえる",kana:"きこえる",  meaning:"聽得到",    group:2, jlpt:"N4" },
  { kanji:"感じる",  kana:"かんじる",  meaning:"感覺",      group:2, jlpt:"N3" },
  { kanji:"考える",  kana:"かんがえる",meaning:"思考",      group:2, jlpt:"N4" },
  { kanji:"調べる",  kana:"しらべる",  meaning:"調查",      group:2, jlpt:"N4" },
  { kanji:"信じる",  kana:"しんじる",  meaning:"相信",      group:2, jlpt:"N3" },
  { kanji:"伝える",  kana:"つたえる",  meaning:"傳達",      group:2, jlpt:"N3" },
  { kanji:"捨てる",  kana:"すてる",    meaning:"丟棄",      group:2, jlpt:"N4" },
  { kanji:"捕まえる",kana:"つかまえる",meaning:"抓住",      group:2, jlpt:"N3" },
  { kanji:"冷える",  kana:"ひえる",    meaning:"變冷",      group:2, jlpt:"N3" },
  { kanji:"増える",  kana:"ふえる",    meaning:"增加",      group:2, jlpt:"N3" },
  { kanji:"与える",  kana:"あたえる",  meaning:"給予",      group:2, jlpt:"N3" },
  { kanji:"生きる",  kana:"いきる",    meaning:"生活",      group:2, jlpt:"N3" },
  { kanji:"落ちる",  kana:"おちる",    meaning:"落下",      group:2, jlpt:"N3" },
  { kanji:"過ぎる",  kana:"すぎる",    meaning:"超過",      group:2, jlpt:"N4" },
  { kanji:"建てる",  kana:"たてる",    meaning:"建造",      group:2, jlpt:"N3" },
  { kanji:"求める",  kana:"もとめる",  meaning:"尋求",      group:2, jlpt:"N2" },
  { kanji:"眺める",  kana:"ながめる",  meaning:"眺望",      group:2, jlpt:"N3" },
  { kanji:"認める",  kana:"みとめる",  meaning:"承認",      group:2, jlpt:"N2" },
  { kanji:"届ける",  kana:"とどける",  meaning:"送達",      group:2, jlpt:"N3" },
  { kanji:"疲れる",  kana:"つかれる",  meaning:"疲勞",      group:2, jlpt:"N4" },
  { kanji:"慣れる",  kana:"なれる",    meaning:"習慣",      group:2, jlpt:"N4" },
  { kanji:"離れる",  kana:"はなれる",  meaning:"分離",      group:2, jlpt:"N3" },
  { kanji:"壊れる",  kana:"こわれる",  meaning:"損壞",      group:2, jlpt:"N3" },
  { kanji:"流れる",  kana:"ながれる",  meaning:"流動",      group:2, jlpt:"N3" },
  { kanji:"濡れる",  kana:"ぬれる",    meaning:"變濕",      group:2, jlpt:"N4" },
  { kanji:"触れる",  kana:"ふれる",    meaning:"碰觸",      group:2, jlpt:"N3" },
  { kanji:"燃える",  kana:"もえる",    meaning:"燃燒",      group:2, jlpt:"N3" },
  { kanji:"揃える",  kana:"そろえる",  meaning:"整理",      group:2, jlpt:"N2" },
  { kanji:"比べる",  kana:"くらべる",  meaning:"比較",      group:2, jlpt:"N3" },
  { kanji:"数える",  kana:"かぞえる",  meaning:"計算",      group:2, jlpt:"N3" },
  { kanji:"加える",  kana:"くわえる",  meaning:"加入",      group:2, jlpt:"N2" },
  { kanji:"混ぜる",  kana:"まぜる",    meaning:"攪拌",      group:2, jlpt:"N3" },
  { kanji:"負ける",  kana:"まける",    meaning:"輸",        group:2, jlpt:"N4" },
  { kanji:"見せる",  kana:"みせる",    meaning:"展示",      group:2, jlpt:"N4" },
  { kanji:"受け入れる",kana:"うけいれる",meaning:"接受",    group:2, jlpt:"N2" },
  { kanji:"浴びる",  kana:"あびる",    meaning:"沐浴",      group:2, jlpt:"N4" },
  { kanji:"生じる",  kana:"しょうじる",meaning:"發生",      group:2, jlpt:"N2" },
  { kanji:"見つける",kana:"みつける",  meaning:"找到",      group:2, jlpt:"N3" },
  { kanji:"告げる",  kana:"つげる",    meaning:"告知",      group:2, jlpt:"N2" },
  { kanji:"恐れる",  kana:"おそれる",  meaning:"恐懼",      group:2, jlpt:"N2" },
  { kanji:"溶ける",  kana:"とける",    meaning:"融化",      group:2, jlpt:"N3" },
  { kanji:"付ける",  kana:"つける",    meaning:"附加",      group:2, jlpt:"N3" },
  { kanji:"切れる",  kana:"きれる",    meaning:"斷、用完",  group:2, jlpt:"N3" },
  { kanji:"当てる",  kana:"あてる",    meaning:"猜中",      group:2, jlpt:"N3" },
  { kanji:"立てる",  kana:"たてる",    meaning:"立起",      group:2, jlpt:"N3" },
  { kanji:"連れる",  kana:"つれる",    meaning:"帶同",      group:2, jlpt:"N4" },
  { kanji:"晴れる",  kana:"はれる",    meaning:"放晴",      group:2, jlpt:"N4" },
  { kanji:"降りる",  kana:"おりる",    meaning:"下車",      group:2, jlpt:"N5" },
  { kanji:"似る",    kana:"にる",      meaning:"相似",      group:2, jlpt:"N3" },
  { kanji:"尽きる",  kana:"つきる",    meaning:"用完",      group:2, jlpt:"N2" },
  { kanji:"慌てる",  kana:"あわてる",  meaning:"慌張",      group:2, jlpt:"N3" },
  { kanji:"甘える",  kana:"あまえる",  meaning:"撒嬌",      group:2, jlpt:"N3" },
  { kanji:"揺れる",  kana:"ゆれる",    meaning:"搖晃",      group:2, jlpt:"N3" },
  { kanji:"溜める",  kana:"ためる",    meaning:"積累",      group:2, jlpt:"N3" },
  { kanji:"諦める",  kana:"あきらめる",meaning:"放棄",      group:2, jlpt:"N3" },
  { kanji:"褒める",  kana:"ほめる",    meaning:"稱讚",      group:2, jlpt:"N3" },
  { kanji:"鍛える",  kana:"きたえる",  meaning:"鍛鍊",      group:2, jlpt:"N2" },
  { kanji:"投げる",  kana:"なげる",    meaning:"投擲",      group:2, jlpt:"N3" },
  { kanji:"逃げる",  kana:"にげる",    meaning:"逃跑",      group:2, jlpt:"N3" },
  { kanji:"掛ける",  kana:"かける",    meaning:"掛、打電話", group:2, jlpt:"N3" },
  { kanji:"まとめる",kana:"まとめる",  meaning:"整理",      group:2, jlpt:"N3" },
  { kanji:"伸びる",  kana:"のびる",    meaning:"延伸",      group:2, jlpt:"N3" },
  { kanji:"覚める",  kana:"さめる",    meaning:"清醒",      group:2, jlpt:"N3" },
  { kanji:"冷める",  kana:"さめる",    meaning:"變冷",      group:2, jlpt:"N3" },
  { kanji:"染める",  kana:"そめる",    meaning:"染色",      group:2, jlpt:"N3" },
  { kanji:"温める",  kana:"あたためる",meaning:"加熱",      group:2, jlpt:"N3" },
  { kanji:"押さえる",kana:"おさえる",  meaning:"壓住",      group:2, jlpt:"N2" },
  { kanji:"植える",  kana:"うえる",    meaning:"種植",      group:2, jlpt:"N3" },
  { kanji:"支える",  kana:"ささえる",  meaning:"支撐",      group:2, jlpt:"N2" },
  { kanji:"広げる",  kana:"ひろげる",  meaning:"展開",      group:2, jlpt:"N3" },
  { kanji:"縮める",  kana:"ちぢめる",  meaning:"縮短",      group:2, jlpt:"N2" },
  { kanji:"整える",  kana:"ととのえる",meaning:"整頓",      group:2, jlpt:"N2" },
  { kanji:"深める",  kana:"ふかめる",  meaning:"加深",      group:2, jlpt:"N2" },
  { kanji:"高める",  kana:"たかめる",  meaning:"提高",      group:2, jlpt:"N2" },
  { kanji:"固める",  kana:"かためる",  meaning:"固定",      group:2, jlpt:"N2" },
  { kanji:"設ける",  kana:"もうける",  meaning:"設置",      group:2, jlpt:"N1" },
  { kanji:"儲ける",  kana:"もうける",  meaning:"獲利",      group:2, jlpt:"N1" },
  { kanji:"述べる",  kana:"のべる",    meaning:"陳述",      group:2, jlpt:"N2" },
  { kanji:"混じる",  kana:"まじる",    meaning:"混合",      group:2, jlpt:"N3" },
  { kanji:"蹴飛ばす",kana:"けとばす",  meaning:"踢飛",      group:1, jlpt:"N1" },
  { kanji:"起き上がる",kana:"おきあがる",meaning:"起身",    group:1, jlpt:"N3" },
  { kanji:"飛び込む",kana:"とびこむ",  meaning:"跳入",      group:1, jlpt:"N3" },
  { kanji:"乗り換える",kana:"のりかえる",meaning:"換車",    group:2, jlpt:"N4" },
  { kanji:"聳え立つ",kana:"そびえたつ",meaning:"高聳",      group:1, jlpt:"N1" },
  { kanji:"見上げる",kana:"みあげる",  meaning:"仰望",      group:2, jlpt:"N3" },
  { kanji:"見下げる",kana:"みさげる",  meaning:"俯視",      group:2, jlpt:"N2" },
  { kanji:"申し上げる",kana:"もうしあげる",meaning:"說（敬）",group:2, jlpt:"N2" },
  { kanji:"差し上げる",kana:"さしあげる",meaning:"給（謙）",group:2, jlpt:"N3" },
  { kanji:"やり直す",kana:"やりなおす",meaning:"重做",      group:1, jlpt:"N3" },
  { kanji:"取り替える",kana:"とりかえる",meaning:"替換",    group:2, jlpt:"N3" },

  // ===== GROUP 3 — 不規則動詞 =====
  { kanji:"来る",    kana:"くる",      meaning:"來",        group:3, jlpt:"N5" },
  { kanji:"する",    kana:"する",      meaning:"做",        group:3, jlpt:"N5" },
  { kanji:"勉強する",kana:"べんきょうする", meaning:"學習",  group:3, jlpt:"N5" },
  { kanji:"運動する",kana:"うんどうする",   meaning:"運動",  group:3, jlpt:"N4" },
  { kanji:"掃除する",kana:"そうじする",     meaning:"打掃",  group:3, jlpt:"N4" },
  { kanji:"洗濯する",kana:"せんたくする",   meaning:"洗衣服", group:3, jlpt:"N4" },
  { kanji:"料理する",kana:"りょうりする",   meaning:"料理",  group:3, jlpt:"N4" },
  { kanji:"電話する",kana:"でんわする",     meaning:"打電話", group:3, jlpt:"N5" },
  { kanji:"説明する",kana:"せつめいする",   meaning:"說明",  group:3, jlpt:"N4" },
  { kanji:"紹介する",kana:"しょうかいする", meaning:"介紹",  group:3, jlpt:"N4" },
  { kanji:"練習する",kana:"れんしゅうする", meaning:"練習",  group:3, jlpt:"N4" },
  { kanji:"準備する",kana:"じゅんびする",   meaning:"準備",  group:3, jlpt:"N4" },
  { kanji:"出発する",kana:"しゅっぱつする", meaning:"出發",  group:3, jlpt:"N4" },
  { kanji:"到着する",kana:"とうちゃくする", meaning:"抵達",  group:3, jlpt:"N4" },
  { kanji:"心配する",kana:"しんぱいする",   meaning:"擔心",  group:3, jlpt:"N4" },
  { kanji:"安心する",kana:"あんしんする",   meaning:"放心",  group:3, jlpt:"N4" },
  { kanji:"利用する",kana:"りようする",     meaning:"利用",  group:3, jlpt:"N3" },
  { kanji:"連絡する",kana:"れんらくする",   meaning:"聯絡",  group:3, jlpt:"N4" },
  { kanji:"相談する",kana:"そうだんする",   meaning:"商量",  group:3, jlpt:"N3" },
  { kanji:"確認する",kana:"かくにんする",   meaning:"確認",  group:3, jlpt:"N3" },
  { kanji:"注文する",kana:"ちゅうもんする", meaning:"點餐",  group:3, jlpt:"N4" },
  { kanji:"予約する",kana:"よやくする",     meaning:"預約",  group:3, jlpt:"N4" },
  { kanji:"研究する",kana:"けんきゅうする", meaning:"研究",  group:3, jlpt:"N3" },
  { kanji:"発表する",kana:"はっぴょうする", meaning:"發表",  group:3, jlpt:"N3" },
  { kanji:"記録する",kana:"きろくする",     meaning:"記錄",  group:3, jlpt:"N3" },
  { kanji:"失敗する",kana:"しっぱいする",   meaning:"失敗",  group:3, jlpt:"N3" },
  { kanji:"成功する",kana:"せいこうする",   meaning:"成功",  group:3, jlpt:"N3" },
  { kanji:"挑戦する",kana:"ちょうせんする", meaning:"挑戰",  group:3, jlpt:"N3" },
  { kanji:"結婚する",kana:"けっこんする",   meaning:"結婚",  group:3, jlpt:"N4" },
  { kanji:"離婚する",kana:"りこんする",     meaning:"離婚",  group:3, jlpt:"N3" },
  { kanji:"旅行する",kana:"りょこうする",   meaning:"旅行",  group:3, jlpt:"N4" },
  { kanji:"散歩する",kana:"さんぽする",     meaning:"散步",  group:3, jlpt:"N4" },
  { kanji:"運転する",kana:"うんてんする",   meaning:"駕駛",  group:3, jlpt:"N4" },
  { kanji:"計算する",kana:"けいさんする",   meaning:"計算",  group:3, jlpt:"N3" },
  { kanji:"翻訳する",kana:"ほんやくする",   meaning:"翻譯",  group:3, jlpt:"N2" },
  { kanji:"参加する",kana:"さんかする",     meaning:"參加",  group:3, jlpt:"N3" },
  { kanji:"卒業する",kana:"そつぎょうする", meaning:"畢業",  group:3, jlpt:"N4" },
  { kanji:"入学する",kana:"にゅうがくする", meaning:"入學",  group:3, jlpt:"N4" },
  { kanji:"留学する",kana:"りゅうがくする", meaning:"留學",  group:3, jlpt:"N3" },
  { kanji:"合格する",kana:"ごうかくする",   meaning:"合格",  group:3, jlpt:"N3" },
  { kanji:"調査する",kana:"ちょうさする",   meaning:"調查",  group:3, jlpt:"N2" },
  { kanji:"開発する",kana:"かいはつする",   meaning:"開發",  group:3, jlpt:"N2" },
  { kanji:"設計する",kana:"せっけいする",   meaning:"設計",  group:3, jlpt:"N2" },
  { kanji:"管理する",kana:"かんりする",     meaning:"管理",  group:3, jlpt:"N2" },
  { kanji:"経営する",kana:"けいえいする",   meaning:"經營",  group:3, jlpt:"N1" },
  { kanji:"質問する",kana:"しつもんする",   meaning:"提問",  group:3, jlpt:"N4" },
  { kanji:"議論する",kana:"ぎろんする",     meaning:"討論",  group:3, jlpt:"N2" },
  { kanji:"判断する",kana:"はんだんする",   meaning:"判斷",  group:3, jlpt:"N2" },
  { kanji:"決定する",kana:"けっていする",   meaning:"決定",  group:3, jlpt:"N2" },
  { kanji:"報告する",kana:"ほうこくする",   meaning:"報告",  group:3, jlpt:"N2" },
  { kanji:"採用する",kana:"さいようする",   meaning:"採用",  group:3, jlpt:"N2" },
  { kanji:"競争する",kana:"きょうそうする", meaning:"競爭",  group:3, jlpt:"N2" },
  { kanji:"応援する",kana:"おうえんする",   meaning:"加油支持", group:3, jlpt:"N3" },
  { kanji:"感謝する",kana:"かんしゃする",   meaning:"感謝",  group:3, jlpt:"N3" },
  { kanji:"尊重する",kana:"そんちょうする", meaning:"尊重",  group:3, jlpt:"N2" },
  { kanji:"信頼する",kana:"しんらいする",   meaning:"信賴",  group:3, jlpt:"N2" },
  { kanji:"注意する",kana:"ちゅういする",   meaning:"注意",  group:3, jlpt:"N3" },
  { kanji:"理解する",kana:"りかいする",     meaning:"理解",  group:3, jlpt:"N3" },
  { kanji:"解決する",kana:"かいけつする",   meaning:"解決",  group:3, jlpt:"N3" },
  { kanji:"実行する",kana:"じっこうする",   meaning:"執行",  group:3, jlpt:"N2" },
  { kanji:"変更する",kana:"へんこうする",   meaning:"變更",  group:3, jlpt:"N2" },
  { kanji:"停止する",kana:"ていしする",     meaning:"停止",  group:3, jlpt:"N2" },
  { kanji:"起動する",kana:"きどうする",     meaning:"啟動",  group:3, jlpt:"N2" },
  { kanji:"製作する",kana:"せいさくする",   meaning:"製作",  group:3, jlpt:"N2" },
  { kanji:"建設する",kana:"けんせつする",   meaning:"建設",  group:3, jlpt:"N2" },
  { kanji:"評価する",kana:"ひょうかする",   meaning:"評估",  group:3, jlpt:"N2" },
  { kanji:"試験する",kana:"しけんする",     meaning:"測試",  group:3, jlpt:"N3" },
  { kanji:"回答する",kana:"かいとうする",   meaning:"回答",  group:3, jlpt:"N3" },
  { kanji:"引っ越しする",kana:"ひっこしする",meaning:"搬家",  group:3, jlpt:"N4" },
  { kanji:"お願いする",kana:"おねがいする", meaning:"拜託",  group:3, jlpt:"N4" },
];

// Remove exact duplicate entries
const seen = new Set();
const VERB_LIST = VERBS.filter(v => {
  const key = v.kana + v.group;
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});
